<?php

/**
 * Copyright © MISPay, Inc. All rights reserved.
 */

$_accessKey = $block->getAccessKey();
$_enabled = $block->isWidgetEnabled();
$_testMode = $block->getTestMode();
?>
<?php if ($_enabled) : ?>
    <?php if ($_testMode) : ?>
        <script defer src="https://widget-sandbox.mispay.co/v1/sdk.js?authorize=<?php echo $_accessKey ?>"></script>
    <?php else : ?>
        <script defer src="https://widget.mispay.co/v1/sdk.js?authorize=<?php echo $_accessKey ?>"></script>
    <?php endif; ?>
<?php endif; ?>